"""Export a reasons network as beliefs.md-compatible markdown."""

from .network import Network


def export_markdown(network: Network) -> str:
    """Generate a beliefs.md-compatible markdown file from the network.

    Nodes are sorted: IN first (alphabetical), then OUT (alphabetical).
    """
    lines = [
        "# Belief Registry",
        "<!-- Generated by reasons export-markdown. Do not edit — operate through reasons. -->",
        "",
        "## Claims",
        "",
    ]

    # Sort: IN first, then OUT, alphabetical within each group
    nodes = sorted(network.nodes.values(), key=lambda n: (n.truth_value != "IN", n.id))

    for node in nodes:
        # Map truth value to beliefs status
        status = node.truth_value
        if status == "OUT" and node.metadata.get("stale_reason"):
            status = "STALE"

        # Get beliefs_type from metadata, default to DERIVED or OBSERVATION
        btype = node.metadata.get("beliefs_type", "")
        if not btype:
            btype = "DERIVED" if node.justifications else "OBSERVATION"

        lines.append(f"### {node.id} [{status}] {btype}")
        lines.append(node.text)

        if node.source:
            lines.append(f"- Source: {node.source}")
        if node.source_hash:
            lines.append(f"- Source hash: {node.source_hash}")
        if node.date:
            lines.append(f"- Date: {node.date}")

        # Collect all antecedents across justifications as depends_on
        all_deps = []
        all_unless = []
        for j in node.justifications:
            for a in j.antecedents:
                if a not in all_deps:
                    all_deps.append(a)
            for o in j.outlist:
                if o not in all_unless:
                    all_unless.append(o)
        if all_deps:
            lines.append(f"- Depends on: {', '.join(all_deps)}")
        if all_unless:
            lines.append(f"- Unless: {', '.join(all_unless)}")

        if status == "STALE" and node.metadata.get("stale_reason"):
            lines.append(f"- Stale reason: {node.metadata['stale_reason']}")
        if node.metadata.get("superseded_by"):
            lines.append(f"- Superseded by: {node.metadata['superseded_by']}")

        lines.append("")

    # Nogoods section
    if network.nogoods:
        lines.append("## Nogoods")
        lines.append("")
        for ng in network.nogoods:
            lines.append(f"### {ng.id}")
            if ng.discovered:
                lines.append(f"- Discovered: {ng.discovered}")
            if ng.resolution:
                lines.append(f"- Resolution: {ng.resolution}")
            lines.append(f"- Affects: {', '.join(ng.nodes)}")
            lines.append("")

    return "\n".join(lines)
